news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from news.views import (
    index,
    NewspaperListView,
    NewspaperDetailView,
    RedactorCreateView,
    RedactorListView,
    TopicListView,
    RedactorDetailView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorDataUpdateView,
    RedactorDeleteView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    NewspaperPublishersUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/update_publishers/",
        NewspaperPublishersUpdateView.as_view(),
        name="update-publishers",
    ),
    path(
        "cars/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/register/", RedactorCreateView.as_view(), name="redactor-register"),
    path(
        "redactors/<int:pk>/update/",
        RedactorDataUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topic-update"),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topic-delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = "news"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls", namespace="news")),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path(r"^pictures/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">

          <div>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.facebook.com/roman.kovalenko.376/" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/Roman28101" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="text-dark my-4 text-sm font-weight-normal">
              &copy;Roman Kovalenko 2023
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <span class="material-icons text-gradient text-primary text-3xl"><a href="{% url 'news:index' %}">home</a></span>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                    Pages
                    <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                        Landing Pages
                      </h6>
                      <a href="{% url 'news:newspaper-list' %}" class="dropdown-item border-radius-md">
                        <span>Newspapers</span>
                      </a>
                      <a href="{% url 'news:redactor-list' %}" class="dropdown-item border-radius-md">
                        <span>Redactors</span>
                      </a>
                      <a href="{% url 'news:topic-list' %}" class="dropdown-item border-radius-md">
                        <span>Topics</span>
                      </a>
                    </div>
                    <div class="d-lg-none">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                        Landing Pages
                      </h6>
                      <a href="{% url 'news:newspaper-list' %}" class="dropdown-item border-radius-md">
                        <span>Newspapers</span>
                      </a>
                      <a href="{% url 'news:redactor-list' %}" class="dropdown-item border-radius-md">
                        <span>Redactors</span>
                      </a>
                      <a href="{% url 'news:topic-list' %}" class="dropdown-item border-radius-md">
                        <span>Topics</span>
                      </a>
                    </div>
                  </div>
                </li>
                <li class="nav-item ms-lg-auto mb-0">
                  {% if user.is_authenticated %}
                  <span class="nav-link nav-link-icon me-2">
                    <span class="d-inline text-sm z-index-1 font-weight-bold me-2">User: <a href="###">{{ user.get_username }}</a></span>
                    <i class="fa fa-sign-out me-1"></i>
                    <a class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" href="{% url 'logout'%}?next={{request.path}}" title="Logout">Logout</a>
                  </span>
                  {% else %}
                  <span class="nav-link nav-link-icon me-2">
                    <i class="fa fa-sign-in me-1"></i>
                    <a class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" href="{% url 'login'%}?next={{request.path}}" title="Login">Login</a>
                  </span>
                  {% endif %}
                </li>

              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination pagination-secondary justify-content-center mt-1">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/searching.html
{% load crispy_forms_filters %}
<div class="container d-flex">
  <form action="" method="get" class="form-group">
    {{ search_form|crispy }}
    <span><input type="submit" value="🔎" class="btn btn-secondary"></span>
  </form>
</div>