news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from news.views import (
    index,
    NewspaperListView,
    NewspaperDetailView,
    RedactorCreateView,
    RedactorListView,
    TopicListView,
    RedactorDetailView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorDataUpdateView,
    RedactorDeleteView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    NewspaperPublishersUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/update_publishers/",
        NewspaperPublishersUpdateView.as_view(),
        name="update-publishers",
    ),
    path(
        "cars/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path("redactors/register/", RedactorCreateView.as_view(), name="redactor-register"),
    path(
        "redactors/<int:pk>/update/",
        RedactorDataUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topic-update"),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topic-delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = "news"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls", namespace="news")),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path(r"^pictures/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/models.py
from PIL import Image
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    img = models.ImageField(
        "Redactor's photo", default="default.png", upload_to="user_images"
    )
    years_of_experience = models.IntegerField(
        default=0, validators=[MaxValueValidator(100), MinValueValidator(0)]
    )

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("news:redactor-detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        super().save()
        image = Image.open(self.img.path)
        if image.height > 256 or image.width > 256:
            resize = (256, 256)
            image.thumbnail(resize)
            image.save(self.img.path)


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ManyToManyField(Topic, related_name="newspapers")
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    class Meta:
        ordering = ["-published_date"]
        verbose_name = "newspaper"
        verbose_name_plural = "newspapers"

    def __str__(self):
        return self.title

news/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from news.models import Redactor, Topic, Newspaper


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class RedactorDataUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["first_name", "last_name", "years_of_experience", "img"]


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."}),
    )


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    topic = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title..."}),
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."}),
    )

news/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from news.forms import (
    RedactorCreationForm,
    RedactorDataUpdateForm,
    RedactorSearchForm,
    NewspaperForm,
    NewspaperSearchForm,
    TopicSearchForm,
)
from news.models import Redactor, Newspaper, Topic


def index(request):
    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "news/index.html", context=context)


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    context_object_name = "newspaper_list"
    template_name = "news/newspaper_list.html"
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        queryset = Newspaper.objects.all()
        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("news:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("news:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("news:newspaper-list")


class NewspaperPublishersUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    fields = ("publishers",)

    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        newspaper = get_object_or_404(Newspaper, pk=pk)
        if request.user in newspaper.publishers.all():
            newspaper.publishers.remove(request.user)
        else:
            newspaper.publishers.add(request.user)
        return redirect("news:newspaper-detail", pk=pk)


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = RedactorSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()
        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.all().prefetch_related("newspapers__topic")


class RedactorCreateView(generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorDataUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorDataUpdateForm
    success_url = reverse_lazy("news:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("news:redactor-list")


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("news:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("news:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("news:topic-list")

templates/news/index.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<body class="presentation-page bg-gray-200">
  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
      <span class="mask bg-gradient-primary opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Welcome to our Newspaper agency</h1>
            <p class="lead text-white mt-3">Here you can find best newspapers <br /> Most skilled redactors in the world! </p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"><span id="state1" countTo={{ num_newspapers }}>0</span>+</h1>
                  <h5 class="mt-3"><a href="{% url 'news:newspaper-list' %}">Newspapers</a></h5>
                  <p class="text-sm font-weight-normal">Already published</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"> <span id="state2" countTo={{ num_redactors }}>0</span>+</h1>
                  <h5 class="mt-3"><a href="{% url 'news:redactor-list' %}">Redactors</a></h5>
                  <p class="text-sm font-weight-normal">Cooperates with us</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"> <span id="state3" countTo={{ num_topics }}>0</span>+</h1>
                  <h5 class="mt-3"><a href="{% url 'news:topic-list' %}">Topics</a></h5>
                  <p class="text-sm font-weight-normal">For all customers</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
    <section class="my-5 py-5">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-4 ms-auto me-auto p-lg-4 mt-lg-0 mt-4">
            <div class="rotating-card-container">
              <div class="card card-rotate card-background card-background-mask-secondary shadow-secondary mt-md-0 mt-5">
                <div class="front front-background" style="background-image: url(https://content.jdmagicbox.com/comp/chandigarh/e4/0172px172.x172.141223162750.q5e4/catalogue/delhi-mansa-marketing-news-agency-chandigarh-sector-22-chandigarh-newspaper-distributors-38m1c.jpg?clr=); background-size: cover;">
                  <div class="card-body py-7 text-center">
                    <i class="material-icons text-white text-4xl my-3">touch_app</i>
                    <h3 class="text-white">We are provides <br /> news for people</h3>
                    <p class="text-white opacity-8">Our main goal is satisfied all customers needs</p>
                  </div>
                </div>
                <div class="back back-background" style="background-image: url(https://www.gcmedia.in/images/newspapper.png); background-size: cover;">
                  <div class="card-body pt-7 text-center">
                    <h3 class="text-white">Join us!</h3>
                    <p class="text-white opacity-8">If you want to be a redactor</p>
                    <a href="{% url 'news:redactor-register'%}" class="btn btn-white btn-sm w-50 mx-auto mt-3">Register</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 ms-auto">
            <div class="row justify-content-start">
              <div class="col-md-6">
                <div class="info">
                  <i class="material-icons text-gradient text-primary text-3xl">language</i>
                  <h5 class="font-weight-bolder mt-3">Worldwide support</h5>
                  <p class="pe-5">Newspapers all over the world</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="info">
                  <i class="material-icons text-gradient text-primary text-3xl">update</i>
                  <h5 class="font-weight-bolder mt-3">Regular updates</h5>
                  <p class="pe-3">Only actual newspapers</p>
                </div>
              </div>
            </div>
            <div class="row justify-content-start mt-5">
              <div class="col-md-6 mt-3">
                <i class="material-icons text-gradient text-primary text-3xl">price_change</i>
                <h5 class="font-weight-bolder mt-3">Save Time & Money</h5>
                <p class="pe-5">Cheaper than paper newspapers</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  <!--   Core JS Files   -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      }
    }
  </script>
  </body>
{% endblock content %}

templates/news/newspaper_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %} {{ newspaper.title }} {% endblock %}


<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6 mt-10">
    <div class="container mt-10">
      <div>
          <div class="card-body m-2">
            <h1>Delete newspaper?</h1>
            <form action="" method="post">
              {% csrf_token %}
              <input type="submit" value="Yes" class="btn btn-primary">
              <a class="btn btn-success" href="{% url 'news:newspaper-list' %}">
                Cancel
              </a>
            </form>
          </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/news/newspaper_detail.html
{% extends "base.html" %}

{% block title %} {{ newspaper.title }} {% endblock %}


<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


  <div class="page-header min-vh-80" style="background-image: url('{{ ASSETS_ROOT }}/img/bg4.jpg')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white">{{ newspaper.title }}</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
  {% if request.user in  newspaper.publishers.all %}
    <form action="{% url 'news:update-publishers' pk=newspaper.pk %}" method="post" novalidate>
      {% csrf_token %}
      <input type="submit" value="Delete me from this newspaper" class="btn btn-danger link-to-page">
    </form>
    {% else%}
    <form action="{% url 'news:update-publishers' pk=newspaper.pk%}" method="post" novalidate>
      {% csrf_token %}
      <input type="submit" value="Assign me to this newspaper" class="btn btn-success link-to-page">
    </form>
    {% endif %}
    <div class="container">
      <div class="d-flex justify-content-center">
          <div class="alert alert-light m-2 text-lg-center">
            <p>{{ newspaper.content }}</p>
            </div>
          </div>
      </div>
      <div class="row">
        <div class="mt-2 text-sm-end">
          {% for topic in newspaper.topic.all %}
            <span class="text-muted ">#{{ topic.name.lower }}</span>
          {% endfor %}
        </div>
      <div>
      <h3>Publish by:</h3>
      <ul>
        {% for publisher in newspaper.publishers.all %}
          <li>{{ publisher.first_name }} {{ publisher.last_name }}</li>
        {% empty %}
          <p>No publishers yet</p>
        {% endfor %}
      </ul>
      <a class="btn btn-outline-secondary" href="{% url 'news:newspaper-update' pk=newspaper.id %}">
        Update
      </a>
      <a class="btn btn-outline-primary" href="{% url 'news:newspaper-delete' pk=newspaper.id %}">
        Delete
      </a>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/news/newspaper_list.html
{% extends "base.html" %}

{% block title %} Newspapers {% endblock %}


<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


  <div class="page-header min-vh-80" style="background-image: url('{{ ASSETS_ROOT }}/img/bg1.jpg')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white">All Newspapers</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
  {% block searching %}
    {% include "includes/searching.html" %}
  {% endblock %}
  <div class="d-block">
      <a href="{% url 'news:newspaper-create' %}" class="btn btn-secondary link-to-page float-end" title="Add newspaper">
        +
      </a>
    </div>
    <div class="container">
      <div class="d-flex justify-content-center  flex-column flex-lg-row">
        {% if newspaper_list %}
        {%for newspaper in newspaper_list%}
          <div class="alert alert-light m-2 text-lg-center">
            <h3><a href="{% url 'news:newspaper-detail' pk=newspaper.id %}">{{newspaper.title}}</a></h3>
            <p>{{ newspaper.content|striptags|truncatechars:400 }}</p>

            <div class="row">
              <div class="mt-2">
                <span class="text-muted">Published {{newspaper.published_date|date:"d E Y в H:i"}}</span>
              </div>
            </div>
          </div>
        {%endfor%}
        {% else %}
          <h3 class="title"><i>There is no newspapers yet</i></h3>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/news/redactor_detail.html
{% extends "base.html" %}

{% block title %} {{ redactor.username }} {% endblock %}


<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


  <div class="page-header min-vh-80" style="background-image: url('{{ ASSETS_ROOT }}/img/bg4.jpg')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white">Redactor info</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6 ">
    <div class="container">
      <form method="post" enctype="multipart/form-data" class="form-register mt-4">

      <div class="d-flex text-muted pt-3 flex-column flex-lg-row">
          <img class="bd-placeholder-img flex-shrink-0 m-2" width="256" height="256" src="{{redactor.img.url}}">
          <div class="pb-3 mb-0 small lh-sm border-bottom">
            <p><strong class="d-block text-gray-dark text-3xl">@{{redactor.username}}</strong></p>
            {%if redactor.email%}
              <p class="text-2xl"><b>Email:</b> <i>{{redactor.email}}</i></p>
            {%endif%}
            {%if redactor.first_name %}
              <p class="text-2xl"><b>First name:</b> <i>{{redactor.first_name}}</i></p>
            {%endif%}
            {%if redactor.last_name %}
              <p class="text-2xl"><b>Last name:</b> <i>{{redactor.last_name}}</i></p>
            {%endif%}
              <p class="text-2xl"><b>Years of experience:</b> <i>{{redactor.years_of_experience}}</i></p>
            <hr>
            <p class="text-2xl"><b>Published newspaper{{ redactor.newspapers.count|pluralize }}:</b>
              <i>
                {% for newspaper in redactor.newspapers.all %}
                <p class="text-2xl"><a href="{% url 'news:newspaper-detail' pk=newspaper.id %}">{{newspaper.title}}</a></p>
                {% empty %}
                  no newspapers
              </i>
            </p>

            {% endfor %}
          </div>
        </div>
      {%csrf_token%}
      <a class="btn btn-outline-secondary" href="{% url 'news:redactor-update' pk=redactor.id %}">
        Update
      </a>
      <a class="btn btn-outline-primary" href="{% url 'news:redactor-delete' pk=redactor.id %}">
        Delete
      </a>
    </form>
    </div>

  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/news/topic_list.html
{% extends "base.html" %}

{% block title %} Topics {% endblock %}


<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


  <div class="page-header min-vh-80" style="background-image: url('{{ ASSETS_ROOT }}/img/bg1.jpg')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white">All topics</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6 ">
  {% block searching %}
    {% include "includes/searching.html" %}
  {% endblock %}
  <div class="d-block">
      <a href="{% url 'news:topic-create' %}" class="btn btn-secondary link-to-page float-end" title="Add new topic">
        +
      </a>
    </div>
    <div class="container">
      <div class="section text-center">
        {% if topic_list %}
        {% for topic in topic_list %}
          <div class="block d-flex flex-column">
            <hr>
            <h3 class="title">#{{ topic.name.lower }}</h3>
          <div class="list">
            <a class="btn btn-outline-secondary" href="{% url 'news:topic-update' pk=topic.id %}">
              Update
            </a>
            <a class="btn btn-outline-primary" href="{% url 'news:topic-delete' pk=topic.id %}">
              Delete
            </a>
            <hr>
          </div>
          </div>


        {% endfor %}
        {% else %}
        <h3 class="title"><i>There is no topics yet</i></h3>
      {% endif %}
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}